name: decollage
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - numpy=1.19.5
  - python=3.6.15
  - python_abi=3.6
  - pytorch=1.10.1
  - torchvision=0.11.2
  - pip:
    - cython==0.29.24
    - h5py==3.1.0
    - imageio==2.15.0
    - open3d==0.15.2
    - opencv-python==4.5.4.58
    - pillow==8.4.0
    - pymcubes==0.1.2
    - scikit-image==0.17.2
    - scikit-learn==0.24.2
    - scipy==1.5.4
    - tqdm==4.64.1

